apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: redmine
  name: redmine-controller
spec:
  replicas: 1
  selector:
    app: redmine
  template:
    metadata:
      name: redmine
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine
        ports:
        - containerPort: 80
        